#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/fixit_connect
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/fixit_connect.service ]; then
			rm /etc/systemd/system/fixit_connect.service /usr/lib/systemd/system/fixit_connect.service /usr/lib/systemd/user/fixit_connect.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/fixit_connect.service /usr/lib/systemd/system/fixit_connect.service
		# try fix error in Ubuntu 18.04
		# Failed to reload fixit_connect.service: Unit fixit_connect.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/fixit_connect.service:10: Executable path is not absolute: pkill -f "fixit_connect --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/fixit_connect.service
		fi
		systemctl daemon-reload
		systemctl enable fixit_connect
		systemctl start fixit_connect
	fi
fi
