name: Windows Build (Manual)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install --triplet x64-windows-static
        shell: pwsh

      - name: Download sciter.dll
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll" -OutFile "sciter.dll"
          mkdir -Force target/release
          Move-Item sciter.dll target/release/
        shell: pwsh

      - name: Build (release)
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-exe
          path: |
            target/x86_64-pc-windows-msvc/release/rustdesk.exe
            target/release/sciter.dll
